# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCvD1bcamRgAIOYcdCkOT6W7MKBLWhTo
"""

import streamlit as st
import pandas as pd

st.set_page_config(layout="wide")
st.title('Test Streamlit')

username_input = st.text_input(
    "username: ",
    value="??????"
)

password_input = st.text_input(
    "Password: ",
    type="password",
    placeholder="pls give password"
)

st.write(username_input,password_input)